apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: slow
provisioner: kubernetes.io/azure-disk
parameters:
 skuName: Standard_LRS
 location: westeurope
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mrp-back
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mrp-back
    spec:
      containers:
      - name: db
        image: devopsdemoregistry.azurecr.io/db:v2
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db  
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mrp-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mrp-front
    spec:
      containers:
      - name: order
        image: devopsdemoregistry.azurecr.io/order:v2
        ports:
        - containerPort: 8888
      - name: web
        image: devopsdemoregistry.azurecr.io/web:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 8080
  - name: order
    port: 8080
    targetPort: 8888
  selector:
    app: mrp-front
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
  - port: 27017
  selector:
    app: mrp-back