apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mrp-back
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mrp-back
    spec:
      containers:
      - name: db
        image: devopsdemoregistry.azurecr.io/db:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db  
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mrp-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mrp-front
    spec:
      containers:
      - name: order
        image: devopsdemoregistry.azurecr.io/order:latest
        ports:
        - containerPort: 8888
      - name: web
        image: devopsdemoregistry.azurecr.io/web:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 8080
  - name: order
    port: 8080
    targetPort: 8888
  selector:
    app: mrp-front
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
  - port: 27017
  selector:
    app: mrp-back