apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 8080
  - name: order
    port: 8080
    targetPort: 8888
  selector:
    app: mrp-front
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
  - port: 27017
  selector:
    app: mrp-back